import React from 'react';
import "./Sid.scss"
const Scroll = () => {
    return (
        <div className="hema">
            <div className="ramp">
            hello ji Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis tenetur id nisi nesciunt. Rem odit facere, recusandae tempora ullam molestias est aut velit modi doloremque asperiores nesciunt voluptate autem veritatis iure cumque porro numquam commodi dicta libero nemo necessitatibus perspiciatis id? Dicta vitae obcaecati praesentium officia adipisci quas itaque debitis, hic deleniti quam, distinctio recusandae maxime facilis accusantium neque dignissimos doloribus numquam harum fugiat molestias rem nisi, ab ducimus. Accusantium saepe alias quidem tenetur totam maiores nobis nulla similique iste eaque reiciendis, ab modi aliquam, adipisci nisi dicta fugiat ipsam, deleniti error sequi eveniet! Vero ad ea aperiam perferendis quam ipsa est quibusdam possimus cupiditate hic laboriosam, consequatur consectetur rerum corrupti sapiente delectus amet facilis excepturi illum laborum incidunt iure. Corporis veritatis odio non. Magni tempora quam error maxime alias reprehenderit nulla dolore facilis. Sequi ea odio suscipit rem iusto quia nam molestias hic. Nam illo suscipit aperiam quaerat ad odit tempora, temporibus nulla unde repudiandae distinctio earum iste numquam velit at maiores impedit aut est voluptates possimus accusantium ab? Libero animi officiis quaerat iusto? Illum quas, odio nihil iste, nesciunt sint, ratione ut vel quo deleniti natus accusamus amet. Exercitationem natus similique reprehenderit nihil! Qui sint nihil quos voluptas!
            hello ji Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis tenetur id nisi nesciunt. Rem odit facere, recusandae tempora ullam molestias est aut velit modi doloremque asperiores nesciunt voluptate autem veritatis iure cumque porro numquam commodi dicta libero nemo necessitatibus perspiciatis id? Dicta vitae obcaecati praesentium officia adipisci quas itaque debitis, hic deleniti quam, distinctio recusandae maxime facilis accusantium neque dignissimos doloribus numquam harum fugiat molestias rem nisi, ab ducimus. Accusantium saepe alias quidem tenetur totam maiores nobis nulla similique iste eaque reiciendis, ab modi aliquam, adipisci nisi dicta fugiat ipsam, deleniti error sequi eveniet! Vero ad ea aperiam perferendis quam ipsa est quibusdam possimus cupiditate hic laboriosam, consequatur consectetur rerum corrupti sapiente delectus amet facilis excepturi illum laborum incidunt iure. Corporis veritatis odio non. Magni tempora quam error maxime alias reprehenderit nulla dolore facilis. Sequi ea odio suscipit rem iusto quia nam molestias hic. Nam illo suscipit aperiam quaerat ad odit tempora, temporibus nulla unde repudiandae distinctio earum iste numquam velit at maiores impedit aut est voluptates possimus accusantium ab? Libero animi officiis quaerat iusto? Illum quas, odio nihil iste, nesciunt sint, ratione ut vel quo deleniti natus accusamus amet. Exercitationem natus similique reprehenderit nihil! Qui sint nihil quos voluptas! hello ji Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis tenetur id nisi nesciunt. Rem odit facere, recusandae tempora ullam molestias est aut velit modi doloremque asperiores nesciunt voluptate autem veritatis iure cumque porro numquam commodi dicta libero nemo necessitatibus perspiciatis id? Dicta vitae obcaecati praesentium officia adipisci quas itaque debitis, hic deleniti quam, distinctio recusandae maxime facilis accusantium neque dignissimos doloribus numquam harum fugiat molestias rem nisi, ab ducimus. Accusantium saepe alias quidem tenetur totam maiores nobis nulla similique iste eaque reiciendis, ab modi aliquam, adipisci nisi dicta fugiat ipsam, deleniti error sequi eveniet! Vero ad ea aperiam perferendis quam ipsa est quibusdam possimus cupiditate hic laboriosam, consequatur consectetur rerum corrupti sapiente delectus amet facilis excepturi illum laborum incidunt iure. Corporis veritatis odio non. Magni tempora quam error maxime alias reprehenderit nulla dolore facilis. Sequi ea odio suscipit rem iusto quia nam molestias hic. Nam illo suscipit aperiam quaerat ad odit tempora, temporibus nulla unde repudiandae distinctio earum iste numquam velit at maiores impedit aut est voluptates possimus accusantium ab? Libero animi officiis quaerat iusto? Illum quas, odio nihil iste, nesciunt sint, ratione ut vel quo deleniti natus accusamus amet. Exercitationem natus similique reprehenderit nihil! Qui sint nihil quos voluptas!
            </div>
        </div>
    )
}

export default Scroll
